# Form implementation generated from reading ui file 'BaoHanh.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtWidgets import *
from PyQt6.uic import loadUi
import sys
import MySQLdb as mdb

class Ui_QuanLyBaoHanh(object):
    def setupUi(self, QuanLyBaoHanh):
        QuanLyBaoHanh.setObjectName("QuanLyBaoHanh")
        QuanLyBaoHanh.resize(704, 600)
        self.centralwidget = QtWidgets.QWidget(parent=QuanLyBaoHanh)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(270, 0, 161, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(40, 80, 71, 21))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(40, 130, 71, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(40, 170, 71, 21))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(320, 80, 47, 14))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(320, 130, 47, 14))
        self.label_6.setObjectName("label_6")
        self.txtMaBH = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.txtMaBH.setGeometry(QtCore.QRect(120, 80, 141, 21))
        self.txtMaBH.setObjectName("txtMaBH")
        self.txtMaSP = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.txtMaSP.setGeometry(QtCore.QRect(120, 130, 141, 21))
        self.txtMaSP.setObjectName("txtMaSP")
        self.txtMaHDX = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.txtMaHDX.setGeometry(QtCore.QRect(120, 180, 141, 21))
        self.txtMaHDX.setObjectName("txtMaHDX")
        self.txtMaNV = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.txtMaNV.setGeometry(QtCore.QRect(370, 80, 141, 21))
        self.txtMaNV.setObjectName("txtMaNV")
        self.txtGhiChu = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.txtGhiChu.setGeometry(QtCore.QRect(370, 130, 141, 71))
        self.txtGhiChu.setObjectName("txtGhiChu")
        self.btnThem = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnThem.setGeometry(QtCore.QRect(50, 240, 75, 23))
        self.btnThem.setObjectName("btnThem")
        self.btnSua = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnSua.setGeometry(QtCore.QRect(180, 240, 75, 23))
        self.btnSua.setObjectName("btnSua")
        self.btnXoa = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnXoa.setGeometry(QtCore.QRect(310, 240, 75, 23))
        self.btnXoa.setObjectName("btnXoa")
        self.tableWidget = QtWidgets.QTableWidget(parent=self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(50, 310, 501, 192))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(5)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        self.pushButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(440, 240, 75, 23))
        self.pushButton.setObjectName("pushButton")
        QuanLyBaoHanh.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=QuanLyBaoHanh)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 704, 22))
        self.menubar.setObjectName("menubar")
        QuanLyBaoHanh.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=QuanLyBaoHanh)
        self.statusbar.setObjectName("statusbar")
        QuanLyBaoHanh.setStatusBar(self.statusbar)

        self.retranslateUi(QuanLyBaoHanh)
        QtCore.QMetaObject.connectSlotsByName(QuanLyBaoHanh)

    def retranslateUi(self, QuanLyBaoHanh):
        _translate = QtCore.QCoreApplication.translate
        QuanLyBaoHanh.setWindowTitle(_translate("QuanLyBaoHanh", "MainWindow"))
        self.label.setText(_translate("QuanLyBaoHanh", "QUẢN LÝ BẢO HÀNH "))
        self.label_2.setText(_translate("QuanLyBaoHanh", "Mã bảo hành"))
        self.label_3.setText(_translate("QuanLyBaoHanh", "Mã Sản phẩm"))
        self.label_4.setText(_translate("QuanLyBaoHanh", "Mã HD Xuất"))
        self.label_5.setText(_translate("QuanLyBaoHanh", "Mã NV"))
        self.label_6.setText(_translate("QuanLyBaoHanh", "Ghi Chú"))
        self.btnThem.setText(_translate("QuanLyBaoHanh", "Thêm "))
        self.btnSua.setText(_translate("QuanLyBaoHanh", "Sửa"))
        self.btnXoa.setText(_translate("QuanLyBaoHanh", "Xóa"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("QuanLyBaoHanh", "Mã BH"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("QuanLyBaoHanh", "Mã SP"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("QuanLyBaoHanh", "Mã HD Xuất"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("QuanLyBaoHanh", "Mã NV"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("QuanLyBaoHanh", "Ghi Chú"))
        self.pushButton.setText(_translate("QuanLyBaoHanh", "Thoát"))

class Baohanh(QMainWindow, Ui_QuanLyBaoHanh):
    def __init__(self):
        super().__init__()
        self.setupUi(self)
        # xử lý sk nút thoát
        self.pushButton.clicked.connect(QApplication.instance().exit)
        # gọi hàm xử hiện dự liệu từ widget lên các text
        self.tableWidget.cellClicked.connect(self.show_selected_data)
        # gọi hàm load dữ liệu 
        self.loaddata()

       
# code sử lý load data lên trang DSBaoHanh
    def loaddata(self):
        db= mdb.connect('localhost','root','','kinhdoanhmaytinh')
        query = db.cursor()
        query.execute("SELECT * FROM tblbaohanh")
        results = query.fetchall()
        #self.tableWidget.setRowCount(len(results))
        self.tableWidget.setRowCount(len(results))
        tablerow =0
        for row in results: 
           self.tableWidget.setItem(tablerow, 0, QTableWidgetItem(str(row[0])))
           self.tableWidget.setItem(tablerow, 1, QTableWidgetItem(str(row[1])))
           self.tableWidget.setItem(tablerow, 2, QTableWidgetItem(str(row[2])))
           self.tableWidget.setItem(tablerow, 3, QTableWidgetItem(str(row[3])))
           self.tableWidget.setItem(tablerow, 4, QTableWidgetItem(str(row[4])))
           #self.WidgetBaoHanh.setItem(tablerow, 5, QTableWidgetItem(str(row[5])))

           tablerow += 1
    def show_selected_data(self, row, column):
        
        # Hiển thị dữ liệu từ hàng được chọn lên các QLineEdit
        self.txtMaBH.setText(self.tableWidget.item(row, 0).text())
        self.txtMaSP.setText(self.tableWidget.item(row, 1).text())
        self.txtMaHDX.setText(self.tableWidget.item(row, 2).text())
        self.txtMaNV.setText(self.tableWidget.item(row, 3).text())
        self.txtGhiChu.setText(self.tableWidget.item(row, 4).text())
# app = QApplication (sys.argv) 
# Widget = QtWidgets.QStackedWidget()
# BaoHanh_show = Baohanh() 
# Widget.addWidget(BaoHanh_show)  
# Widget.setFixedHeight(800) 
# Widget.setFixedWidth(600) 
# Widget.show()
# app.exec()

