# Form implementation generated from reading ui file 'DSBanH.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.
# python -m PyQt6.uic.pyuic <name file ui>.ui -o <name file python>.py

from  PyQt6 import QtCore,QtGui,QtWidgets,uic
from PyQt6.QtWidgets import *
from PyQt6.uic import loadUi
import sys
import MySQLdb as mdb

# code sử lý giao diện .ui
class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.hoadobanhang = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.hoadobanhang.setGeometry(QtCore.QRect(20, 50, 781, 521))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.hoadobanhang.setFont(font)
        self.hoadobanhang.setObjectName("hoadobanhang")
        self.label_2 = QtWidgets.QLabel(parent=self.hoadobanhang)
        self.label_2.setGeometry(QtCore.QRect(20, 30, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.txtMaHD = QtWidgets.QLineEdit(parent=self.hoadobanhang)
        self.txtMaHD.setGeometry(QtCore.QRect(150, 30, 113, 20))
        self.txtMaHD.setObjectName("txtMaHD")
        self.label_3 = QtWidgets.QLabel(parent=self.hoadobanhang)
        self.label_3.setGeometry(QtCore.QRect(10, 90, 131, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.txtTenKhach = QtWidgets.QLineEdit(parent=self.hoadobanhang)
        self.txtTenKhach.setGeometry(QtCore.QRect(150, 90, 113, 20))
        self.txtTenKhach.setObjectName("txtTenKhach")
        self.txtTenNV = QtWidgets.QLineEdit(parent=self.hoadobanhang)
        self.txtTenNV.setGeometry(QtCore.QRect(400, 90, 113, 20))
        self.txtTenNV.setText("")
        self.txtTenNV.setObjectName("txtTenNV")
        self.label_4 = QtWidgets.QLabel(parent=self.hoadobanhang)
        self.label_4.setGeometry(QtCore.QRect(270, 90, 121, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.btnSua = QtWidgets.QPushButton(parent=self.hoadobanhang)
        self.btnSua.setGeometry(QtCore.QRect(580, 40, 91, 23))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.btnSua.setFont(font)
        self.btnSua.setObjectName("btnSua")
        self.btnthem = QtWidgets.QPushButton(parent=self.hoadobanhang)
        self.btnthem.setGeometry(QtCore.QRect(580, 70, 91, 23))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.btnthem.setFont(font)
        self.btnthem.setObjectName("btnthem")
        self.btnxoa = QtWidgets.QPushButton(parent=self.hoadobanhang)
        self.btnxoa.setGeometry(QtCore.QRect(580, 100, 91, 23))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.btnxoa.setFont(font)
        self.btnxoa.setObjectName("btnxoa")
        self.btnbackMN = QtWidgets.QPushButton(parent=self.hoadobanhang)
        self.btnbackMN.setGeometry(QtCore.QRect(580, 130, 91, 23))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.btnbackMN.setFont(font)
        self.btnbackMN.setObjectName("btnbackMN")
        self.label_12 = QtWidgets.QLabel(parent=self.hoadobanhang)
        self.label_12.setGeometry(QtCore.QRect(290, 30, 111, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.txtNgayLap = QtWidgets.QLineEdit(parent=self.hoadobanhang)
        self.txtNgayLap.setGeometry(QtCore.QRect(400, 30, 113, 20))
        self.txtNgayLap.setObjectName("txtNgayLap")
        self.WidgetBanhang = QtWidgets.QTableWidget(parent=self.hoadobanhang)
        self.WidgetBanhang.setGeometry(QtCore.QRect(30, 190, 691, 251))
        self.WidgetBanhang.setColumnCount(5)
        self.WidgetBanhang.setObjectName("WidgetBanhang")
        self.WidgetBanhang.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.WidgetBanhang.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.WidgetBanhang.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.WidgetBanhang.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.WidgetBanhang.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.WidgetBanhang.setHorizontalHeaderItem(4, item)
        self.WidgetBanhang.horizontalHeader().setDefaultSectionSize(122)
        self.WidgetBanhang.horizontalHeader().setMinimumSectionSize(48)
        self.pushButton = QtWidgets.QPushButton(parent=self.hoadobanhang)
        self.pushButton.setGeometry(QtCore.QRect(20, 140, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(230, -10, 391, 61))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label.setFont(font)
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.hoadobanhang.setTitle(_translate("MainWindow", "Danh Sách Hóa Đơn"))
        self.label_2.setText(_translate("MainWindow", "Mã Hóa Đơn"))
        self.label_3.setText(_translate("MainWindow", "Tên Khách Hàng"))
        self.label_4.setText(_translate("MainWindow", "Tên Nhân Viên"))
        self.btnSua.setText(_translate("MainWindow", "Sửa"))
        self.btnthem.setText(_translate("MainWindow", "Thêm mới"))
        self.btnxoa.setText(_translate("MainWindow", "Loại Bỏ"))
        self.btnbackMN.setText(_translate("MainWindow", "Thoát"))
        self.label_12.setText(_translate("MainWindow", "Ngày Lập"))
        item = self.WidgetBanhang.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Mã Hóa Đơn"))
        item = self.WidgetBanhang.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Tên Khách Hàng"))
        item = self.WidgetBanhang.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Tên Nhân Viên"))
        item = self.WidgetBanhang.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Ngày Lập"))
        item = self.WidgetBanhang.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Tổng Tiền"))
        self.pushButton.setText(_translate("MainWindow", "Hóa Đơn Chi Tiết"))
        self.label.setText(_translate("MainWindow", "Quản Lý Bán Hàng"))
# code sử lý sự kiện 

class DSBH(QMainWindow, Ui_MainWindow):
    def __init__(self):
        super().__init__()
        self.setupUi(self)
        self.hide()
        #show dữ liệu từ Widget lên Textbox
        self.WidgetBanhang.cellClicked.connect(self.show_selected_data)
        self.loaddata()
        # code thoát chương trình   
        #self.btnbackMN.clicked.connect(self.show_Menu)
        self.btnbackMN.clicked.connect(QApplication.instance().exit)
        # code chuyển tab 
        # code tab bán hàng
     
# Load Data lên widget 
    def loaddata(self):
        db= mdb.connect('localhost','root','','cdn_btl')
        query = db.cursor()
        query.execute("SELECT * FROM hoadonban_giatri")
        results = query.fetchall()
        #self.tableWidget.setRowCount(len(results))
        self.WidgetBanhang.setRowCount(len(results))
        tablerow =0
        for row in results: 
           self.WidgetBanhang.setItem(tablerow, 0, QTableWidgetItem(str(row[0])))
           self.WidgetBanhang.setItem(tablerow, 1, QTableWidgetItem(str(row[1])))
           self.WidgetBanhang.setItem(tablerow, 2, QTableWidgetItem(str(row[2])))
           self.WidgetBanhang.setItem(tablerow, 3, QTableWidgetItem(str(row[3])))
           self.WidgetBanhang.setItem(tablerow, 4, QTableWidgetItem(str(row[4])))
           #self.tableWidget.setItem(tablerow, 5, QTableWidgetItem(str(row[5])))
           #self.tableWidget.setItem(tablerow, 6, QTableWidgetItem(str(row[6])))
           #self.tableWidget.setItem(tablerow, 7, QTableWidgetItem(str(row[7])))
           #self.tableWidget.setItem(tablerow, 8, QTableWidgetItem(str(row[8])))
           #self.tableWidget.setItem(tablerow, 9, QTableWidgetItem(str(row[9])))
           tablerow += 1
    # code trở lại trang menu
    # def show_Menu(self):
    #     # Tạo một instance của trang DSBH
    #     self.menu_window = MenuTong()
    #     # Hiển thị trang DSBH
    #     self.menu_window.show() 
# hiện Dữ liệu từ widget lên text box

    def show_selected_data(self, row, column):
        try:
            # Hiển thị dữ liệu từ hàng được chọn lên các QLineEdit
            self.txtMaHD.setText(self.WidgetBanhang.item(row, 0).text())
            self.txtTenKhach.setText(self.WidgetBanhang.item(row, 1).text())
            self.txtTenNV.setText(self.WidgetBanhang.item(row, 2).text())
            self.txtNgayLap.setText(self.WidgetBanhang.item(row, 3).text())
            # self.txtSdtNCC.setText(self.tableWidget.item(row, 4).text())
            # self.txtSoLuong.setText(self.tableWidget.item(row, 5).text())
            # self.txtNVLap.setText(self.tableWidget.item(row, 6).text())
            # self.txtNgayNhap.setText(self.tableWidget.item(row, 7).text())
        except Exception as e:
            print(f"Error in show_selected_data: {e}")
#Thêm 1 hóa đơn 

#-------------------------------------------------------------------------------------  
app = QApplication (sys.argv) 
Widget = QtWidgets.QStackedWidget()
DSBH1 = DSBH() 
Widget.addWidget(DSBH1)  
Widget.setFixedHeight(600) 
Widget.setFixedWidth(800) 
Widget.show()
app.exec()